### ISSUE TITLE
BASILISK FEEDBACK

### ISSUE THREAD

**Issue by Deeney05** [galacticcouncil/Basilisk-ui-old#904]
testing some swap features on basilisk was quiet easy and convenient, I didn't encounter any error or bug but I have some few suggestions that might help the cause 
Firstly i think they should be a pool to help buid a more stable farm 
Secondly there should be a search bar to help for easy access to tokens and farms

**Comment by neni21** [comment]
bXgk69CPDeQzRZwf9DN458n5cnB2vU3Hj7bWHxZsBPtyt69xB

This is a great testnet sir
God luck for this project 
Easy to use. And i don't found some bugs

**Comment by Andka68** [comment]
GhC5Q6tKWwp7GXCB8rPToXavD1yzrZWJQRjTCCGp9GS5j5B
Thank you for providing the opportunity to participate in the crowdlon and now for testing the services. I hope this project succeeds!
  According to the test itself, I probably, like other participants, noticed the absence of write-offs from the account after each operation. The numbers didn't go down. Otherwise, everything worked quickly and without comment.

**Comment by Cryptograsi** [comment]
I joined the basilisk testnet with the bXmibBnmEbK21RuCST5Fxq2EUmtirjKBU63vZB1aotBtqiLKF wallet. Faucet works fine, I had no difficulties getting test tokens. I did a lot of swap transactions and the transactions were completed very quickly and without any problems. You have created a platform that works well, I have enjoyed the testnet. The platform will be even better with the addition of new features. Congrats Basilisk Team
