### ISSUE TITLE
Bug: Bugs and fixes

### ISSUE THREAD

**Issue by MiniBikini12** [galacticcouncil/Basilisk-ui-old#960]
### Possible Fix

Hello, I conducted cryptocurrency exchanges on your site, at one moment I noticed that I can transfer more KSM than it should actually be (10 times)
I would like to see more design details on the site and more cryptocurrencies for exchanges in the future.
And probably the most important thing, I would like the opportunity to insist on a schedule so that you can determine the price (15 minutes, 1 hour, 5 hours, 1 day)
### Context

Add more elements to the interface. You can add day and night themes. Fix the moment with the exchange of cryptocurrencies, with this revealed problems.

My wallet address
5E6yJCHdHZ6anugGmPwHRZrtzLntzf5hwipNB7E7bZrLW4gD

**Comment by Cubo25** [comment]
1. Hello, I conducted cryptocurrency exchanges on your site, at one moment I noticed that I can transfer more KSM than it should actually be (10 times) - Please try our production https://app.basilisk.cloud/#/wallet - if problem persists provide screenshot or more evidence of the bug.

2. I would like to see more design details on the site and more cryptocurrencies for exchanges in the future.
Please try our production https://app.basilisk.cloud/#/wallet where you can already see some design changes of our platform.

3. And probably the most important thing, I would like the opportunity to insist on a schedule so that you can determine the price (15 minutes, 1 hour, 5 hours, 1 day)
The price graph feature If you meant that is heavily requested feature and it is included on our roadmap.


Thanks for understanding and I hope you enjoy the https://app.basilisk.cloud/#/wallet 🙏🏻
