### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#975]
Design for the asset list was nearly finished. However there are a couple of things that need to be taken care of in order to satisfy the requirements described in our story.

Here's the outstanding to-do list:

- [x] Reorder stats & table to match in the following order: spendable, total, locked (locked within the list it stays where it is)
- [x] Add Share token list item design (LP token)
- [x] Add toggle for 'in pools'
- [x] Empty state (when the user has 0 balance for every asset) 
- [x] Loading state (when the balances etc. are being fetched)
- [x] Add additional actions per asset type (share/native/bridged) as described in the story
- [x] Replace the tooltip contents for 'locked' to be a simple plain text disclaimer
- [x] Try an alternative design for displaying the active 'fee payment asset' in the list
- [x] hide small balances toggle -> and rename it to show all available assets (but hide it anyways for this version)

**Comment by Cubo25** [comment]
1. Reorder stats & table to match in the following order: spendable, total, locked (locked within the list it stays where it is) ❌ - spotPrice should not be displayed as a column but should be displayed in asset list detail
https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9?node-id=4284:54932#218184653

2. Add Share token list item design (LP token) ❌ - display value should be displayed in detail
https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9?node-id=4284:54932#218186895

3. Add toggle for 'in pools' ❌ - please make this toggle consistent for all the states(empty/loading/loaded)  https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9?node-id=4284:54932#218166071

4. Empty state (when the user has 0 balance for every asset) ✅

5. Loading state (when the balances etc. are being fetched) ✅

6. Add additional actions per asset type (share/native/bridged) as described in the story ❌ - please provide actions according to the type of asset. That means showcase actions for the native/bridged asset and also show the actions for shared token

7. Replace the tooltip for 'locked' to be a simple plain text disclaimer ❌
tooltip with info still there 

8. Try an alternative design for displaying the active 'fee payment asset' in the list ❌ - I do not see this anywhere in figma - it was just showcased in discord channel 

9. hide small balances toggle -> and rename it to show all available assets (but hide it anyways for this version) ❌ - make it consistent and mark it as higher version
https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9?node-id=4284:54932#218166071

**Comment by maht0rz** [comment]
After consulting @jakubgregus we have decided that we should:
- scrape the 'empty state' and show 'all available assets' by default. This also means that the 'show all available assets' toggle needs to go away.
- separate Share tokens into a sub-table with a header 'Share Tokens'. so a subtitle should be added to the table that will separate the asset list 'in half'.
- get rid of the 'in pools' toggle entirely, we won't implement this at this point. However the design for those toggles can 'stay' in the design for future use.

**Comment by samborek** [comment]
Let's sync tomorrow to go through all of this. 
Sub table was my initial thinking since  Share tokens don't have the Spot price, but I scrapped that idea to keep It together since it's easier to browse within one container with an infinite scroll or so. 

@maht0rz  if we do a separate table for Share Tokens do we display different data for tables or what is Your logic for this approach? 
How many assets do we want to show before we add pagination? 

1. Spot price was mentioned in the story but not specifically in Asset Detail. This usually is visible upfront to compare the price of assets. 
2. Added ✅
3. Fixed ✅

6. What's our intention here? 
This is what we got now under More(three dots) Do you want to pull that upfront? Change the featured actions for LP to Add/Remove liquidity? 
This will need a change of this design and components we've already done and implemented. Please be precise. 
 ![image.png](https://images.zenhubusercontent.com/62b598f995f0a629935cccd9/87c2026d-9068-45e0-b575-ebe6321040cf)

7. It's a simple text tooltip just with value within. But I can remove it. 
8. If you can't find it please ask - but overall if it's decided over chat it should be considered done, I think? 
9. Fixed. Hidden for future use ✅

**Comment by maht0rz** [comment]
After talking to @samborek we have came to a conclusion that the 'spot price' can be removed from the current version and can be added in a standalone story entirely. Additionally, thanks to the Share token table separation, we can fit 'add' and 'remove' liquidity actions as priority for share token actions.

cc @jakubgregus

**Comment by Cubo25** [comment]
Conclusion from the last comments : 
 

- [x] spotprice column deleted
- [x] separate Share tokens into a sub-table with a header 'Share Tokens'. so a subtitle should be added to the table that will separate the asset list 'in half'.
- [x] actions add / remove liquidity to be priority actions for shared tokens
- [x] set as fee payment asset label 
- [x] scrape the 'empty state' and show 'all available assets' by default. This also means that the 'show all available assets' toggle needs to go away.
- [x] get rid of the 'in pools' toggle entirely, we won't implement this at this point. However the design for those toggles can 'stay' in the design for future use. (just hide them for now please)
